spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true # SQL? ??? ???? ??
        use_sql_comments: true # ?? ??? ??? ?? ??
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:soulduse;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximumPoolSize: 10

